import { FREQUENT_EMOJIS } from './categories';

export interface EmojiEntry {
  char: string;
  keywords: string;
}

export interface EmojiGroup {
  id: string;
  label: string;
  emojis: EmojiEntry[];
}

function entries(pairs: [string, string][]): EmojiEntry[] {
  return pairs.map(([char, keywords]) => ({ char, keywords }));
}

const FACES: EmojiEntry[] = entries([
  ['😀', 'cara feliz sonrisa grin happy'],
  ['😃', 'cara sonrisa alegre happy'],
  ['😄', 'cara risa feliz happy'],
  ['😁', 'cara sonrisa dientes happy'],
  ['😆', 'cara risa carcajada laugh'],
  ['😅', 'cara risa sudor nervioso sweat'],
  ['😂', 'risa llanto lol joy lagrimas'],
  ['🤣', 'risa suelo lol rofl'],
  ['🙂', 'cara leve sonrisa smile'],
  ['🙃', 'cara invertida upside'],
  ['😉', 'guiño wink'],
  ['😊', 'sonrisa rubor feliz blush'],
  ['😇', 'angel halo inocente'],
  ['🥰', 'amor corazones love enamorado'],
  ['😍', 'ojos corazon amor love'],
  ['🤩', 'estrellas asombro wow star'],
  ['😘', 'beso kiss amor'],
  ['😗', 'beso kiss'],
  ['😚', 'beso ojos cerrados kiss'],
  ['😋', 'rico delicioso yummy lengua'],
  ['😛', 'lengua tongue'],
  ['😜', 'lengua guiño tongue wink'],
  ['🤪', 'loco zany crazy'],
  ['😝', 'lengua ojos cerrados tongue'],
  ['🤑', 'dinero money plata billete'],
  ['🤗', 'abrazo hug'],
  ['🤭', 'risa mano oops'],
  ['🤫', 'silencio shh callar'],
  ['🤔', 'pensar duda thinking'],
  ['🤐', 'boca cerrada zip silencio'],
  ['🤨', 'ceja duda eyebrow'],
  ['😐', 'neutral serio'],
  ['😑', 'inexpresivo serio'],
  ['😶', 'sin boca silencio'],
  ['😏', 'picaro smirk'],
  ['😒', 'fastidio unamused'],
  ['🙄', 'ojos arriba roll eyes'],
  ['😬', 'mueca grimace'],
  ['😌', 'aliviado calma relieved'],
  ['😔', 'triste pensativo sad'],
  ['😪', 'sueño cansado sleepy'],
  ['😴', 'dormido sleep zzz'],
  ['😷', 'mascara enfermo mask'],
  ['🤒', 'enfermo fiebre sick'],
  ['🤕', 'herido venda hurt'],
  ['🤢', 'nausea asco sick'],
  ['🤮', 'vomito vomit'],
  ['🤧', 'estornudo resfriado sneeze'],
  ['🥵', 'calor hot sudor'],
  ['🥶', 'frio cold congelado'],
  ['😵', 'mareado dizzy'],
  ['🤯', 'mente explota shock wow'],
  ['🥳', 'fiesta party celebracion'],
  ['😎', 'genial cool gafas sol'],
  ['🤓', 'nerd gafas geek'],
  ['🧐', 'monoculo curioso'],
  ['😕', 'confundido confused'],
  ['😟', 'preocupado worried'],
  ['🙁', 'triste leve frown'],
  ['☹️', 'triste frown'],
  ['😮', 'sorpresa boca abierta'],
  ['😯', 'sorpresa hushed'],
  ['😲', 'asombro astonished'],
  ['😳', 'sonrojado flushed'],
  ['🥺', 'suplica ojos pleading'],
  ['😦', 'asustado frown'],
  ['😧', 'angustia anguish'],
  ['😨', 'miedo fearful'],
  ['😰', 'ansiedad sudor anxious'],
  ['😥', 'triste alivio sad'],
  ['😢', 'llanto lagrima cry sad'],
  ['😭', 'llorar mucho sob cry'],
  ['😱', 'grito miedo scream'],
  ['😖', 'frustrado confounded'],
  ['😣', 'persistir perseverar'],
  ['😞', 'decepcionado disappointed'],
  ['😓', 'sudor downcast'],
  ['😩', 'cansado weary'],
  ['😫', 'agotado tired'],
  ['🥱', 'bostezo yawn cansado'],
  ['😤', 'enojo vapor triumph'],
  ['😡', 'enojado rojo angry rage'],
  ['😠', 'molesto angry'],
  ['🤬', 'maldicion groseria swear'],
  ['😈', 'diablo travieso devil'],
  ['👿', 'demonio enojado imp'],
  ['💀', 'calavera muerte skull'],
  ['💩', 'caca poo'],
  ['🤡', 'payaso clown'],
  ['👻', 'fantasma ghost'],
  ['👽', 'alien extraterrestre'],
  ['🤖', 'robot bot'],
  ['🎃', 'calabaza halloween'],
  ['😺', 'gato sonrisa cat'],
  ['😻', 'gato amor cat love'],
  ['🙀', 'gato susto cat'],
]);

const GESTURES: EmojiEntry[] = entries([
  ['👋', 'saludo mano hola wave'],
  ['🤚', 'mano levantada hand'],
  ['✋', 'mano alto stop hand'],
  ['🖐️', 'mano dedos hand'],
  ['👌', 'ok perfecto'],
  ['🤌', 'dedos italiano pinch'],
  ['🤏', 'poquito pinch'],
  ['✌️', 'paz victoria peace'],
  ['🤞', 'cruzar dedos suerte luck'],
  ['🤟', 'te amo love hand'],
  ['🤘', 'rock cuernos'],
  ['🤙', 'llamame call'],
  ['👈', 'izquierda left'],
  ['👉', 'derecha right'],
  ['👆', 'arriba up'],
  ['👇', 'abajo down'],
  ['☝️', 'indice arriba point'],
  ['👍', 'pulgar arriba like bien thumbs up'],
  ['👎', 'pulgar abajo mal dislike thumbs down'],
  ['✊', 'puño fist'],
  ['👊', 'puño golpe punch'],
  ['👏', 'aplausos clap'],
  ['🙌', 'manos arriba celebracion raise'],
  ['👐', 'manos abiertas open'],
  ['🤝', 'apreton manos acuerdo handshake'],
  ['🙏', 'rezar gracias por favor pray'],
  ['💪', 'fuerza musculo strong'],
  ['🦾', 'brazo mecanico fuerza'],
  ['✍️', 'escribir mano writing'],
  ['👀', 'ojos mirar eyes'],
  ['🧠', 'cerebro mente brain'],
  ['👶', 'bebe baby'],
  ['🧒', 'niño child'],
  ['👦', 'niño boy'],
  ['👧', 'niña girl'],
  ['🧑', 'persona adulto person'],
  ['👨', 'hombre man'],
  ['👩', 'mujer woman'],
  ['🧓', 'anciano elder'],
  ['👮', 'policia police'],
  ['👷', 'obrero construccion worker'],
  ['💂', 'guardia guard'],
  ['🕵️', 'detective espia'],
  ['👨‍⚕️', 'doctor medico salud'],
  ['👨‍🍳', 'chef cocinero cook'],
  ['👨‍🏫', 'profesor maestro teacher'],
  ['👨‍💻', 'programador dev tech'],
  ['👨‍🔧', 'mecanico tecnico'],
  ['👨‍🌾', 'agricultor farmer'],
  ['👨‍🚀', 'astronauta space'],
  ['🧑‍🚒', 'bombero firefighter'],
  ['🦸', 'heroe superheroe hero'],
  ['🦹', 'villano villain'],
  ['🧙', 'mago wizard'],
  ['🧚', 'hada fairy'],
  ['👼', 'angel bebe'],
  ['🤰', 'embarazada pregnant'],
  ['🚶', 'caminar walk'],
  ['🏃', 'correr run'],
  ['💃', 'bailar dance'],
  ['🕺', 'bailar hombre dance'],
  ['👯', 'fiesta bailar party'],
  ['🧘', 'yoga meditar zen'],
  ['👤', 'silueta persona user'],
  ['👥', 'personas usuarios users'],
  ['🗣️', 'hablar voz speak'],
]);

const NATURE: EmojiEntry[] = entries([
  ['🐶', 'perro dog mascota'],
  ['🐱', 'gato cat mascota'],
  ['🐭', 'raton mouse'],
  ['🐹', 'hamster'],
  ['🐰', 'conejo rabbit'],
  ['🦊', 'zorro fox'],
  ['🐻', 'oso bear'],
  ['🐼', 'panda'],
  ['🐨', 'koala'],
  ['🐯', 'tigre tiger'],
  ['🦁', 'leon lion'],
  ['🐮', 'vaca cow'],
  ['🐷', 'cerdo pig'],
  ['🐸', 'rana frog'],
  ['🐵', 'mono monkey'],
  ['🐔', 'gallina chicken'],
  ['🐧', 'pinguino penguin'],
  ['🐦', 'pajaro bird'],
  ['🦅', 'aguila eagle'],
  ['🦉', 'buho owl'],
  ['🦇', 'murcielago bat'],
  ['🐺', 'lobo wolf'],
  ['🐗', 'jabali boar'],
  ['🐴', 'caballo horse'],
  ['🦄', 'unicornio unicorn'],
  ['🐝', 'abeja bee'],
  ['🐛', 'gusano bug'],
  ['🦋', 'mariposa butterfly'],
  ['🐌', 'caracol snail'],
  ['🐞', 'mariquita ladybug'],
  ['🐜', 'hormiga ant'],
  ['🕷️', 'araña spider'],
  ['🦂', 'escorpion scorpion'],
  ['🐢', 'tortuga turtle'],
  ['🐍', 'serpiente snake'],
  ['🦎', 'lagarto lizard'],
  ['🐙', 'pulpo octopus'],
  ['🦑', 'calamar squid'],
  ['🦐', 'camaron shrimp'],
  ['🦀', 'cangrejo crab'],
  ['🐟', 'pez fish'],
  ['🐠', 'pez tropical fish'],
  ['🐬', 'delfin dolphin'],
  ['🐳', 'ballena whale'],
  ['🦈', 'tiburon shark'],
  ['🐊', 'cocodrilo crocodile'],
  ['🐘', 'elefante elephant'],
  ['🦏', 'rinoceronte rhino'],
  ['🐪', 'camello camel'],
  ['🦒', 'jirafa giraffe'],
  ['🐃', 'bufalo buffalo'],
  ['🐎', 'caballo carrera horse'],
  ['🐖', 'cerdo pig'],
  ['🐑', 'oveja sheep'],
  ['🐐', 'cabra goat'],
  ['🦌', 'ciervo deer'],
  ['🐕', 'perro dog'],
  ['🦮', 'perro guia dog'],
  ['🐈', 'gato cat'],
  ['🦔', 'erizo hedgehog'],
  ['🐇', 'conejo rabbit'],
  ['🌱', 'planta brote plant'],
  ['🌿', 'hierba hojas herb'],
  ['🍀', 'trebol suerte clover'],
  ['🌵', 'cactus'],
  ['🌳', 'arbol tree'],
  ['🌲', 'pino arbol tree'],
  ['🌴', 'palmera palm'],
  ['🌷', 'tulipan flor tulip'],
  ['🌸', 'flor cerezo blossom'],
  ['🌹', 'rosa flor rose'],
  ['🌺', 'flor hibisco'],
  ['🌻', 'girasol sunflower'],
  ['🌼', 'margarita flor'],
  ['💐', 'ramo flores bouquet'],
  ['🍄', 'hongo seta mushroom'],
  ['🌍', 'tierra mundo earth'],
  ['🌎', 'tierra mundo americas earth'],
  ['🌙', 'luna moon noche'],
  ['⭐', 'estrella star'],
  ['🌟', 'estrella brillo star'],
  ['✨', 'destellos brillo sparkles'],
  ['⚡', 'rayo electrico lightning'],
  ['🔥', 'fuego llama fire'],
  ['💧', 'gota agua water'],
  ['🌊', 'ola mar agua wave'],
  ['☀️', 'sol soleado sun'],
  ['⛅', 'nube sol cloud'],
  ['☁️', 'nube cloud'],
  ['🌧️', 'lluvia rain'],
  ['⛈️', 'tormenta storm'],
  ['❄️', 'nieve copo snow'],
  ['☃️', 'muñeco nieve snowman'],
  ['🌈', 'arcoiris rainbow'],
]);

const FOOD: EmojiEntry[] = entries([
  ['🍏', 'manzana verde apple'],
  ['🍎', 'manzana apple fruta'],
  ['🍐', 'pera pear'],
  ['🍊', 'naranja orange'],
  ['🍋', 'limon lemon'],
  ['🍌', 'banana platano'],
  ['🍉', 'sandia watermelon'],
  ['🍇', 'uvas grapes'],
  ['🍓', 'fresa strawberry'],
  ['🫐', 'arandano blueberry'],
  ['🍈', 'melon'],
  ['🍒', 'cereza cherry'],
  ['🍑', 'durazno peach'],
  ['🥭', 'mango'],
  ['🍍', 'piña pineapple'],
  ['🥥', 'coco coconut'],
  ['🥝', 'kiwi'],
  ['🍅', 'tomate tomato'],
  ['🍆', 'berenjena eggplant'],
  ['🥑', 'aguacate avocado'],
  ['🥦', 'brocoli broccoli'],
  ['🥬', 'lechuga verdura'],
  ['🥒', 'pepino cucumber'],
  ['🌶️', 'chile picante pepper'],
  ['🌽', 'maiz corn'],
  ['🥕', 'zanahoria carrot'],
  ['🧄', 'ajo garlic'],
  ['🧅', 'cebolla onion'],
  ['🥔', 'papa patata potato'],
  ['🍠', 'camote batata'],
  ['🥐', 'croissant'],
  ['🥖', 'baguette pan bread'],
  ['🍞', 'pan bread'],
  ['🥨', 'pretzel'],
  ['🧀', 'queso cheese'],
  ['🥚', 'huevo egg'],
  ['🍳', 'huevo frito sarten'],
  ['🥓', 'tocino bacon'],
  ['🥩', 'carne steak'],
  ['🍗', 'pollo muslo chicken'],
  ['🍖', 'carne hueso meat'],
  ['🌭', 'hotdog perro caliente'],
  ['🍔', 'hamburguesa burger'],
  ['🍟', 'papas fritas fries'],
  ['🍕', 'pizza'],
  ['🥪', 'sandwich'],
  ['🌮', 'taco'],
  ['🌯', 'burrito'],
  ['🥗', 'ensalada salad'],
  ['🥘', 'paella guiso'],
  ['🍝', 'pasta spaghetti'],
  ['🍜', 'ramen sopa noodles'],
  ['🍲', 'sopa olla stew'],
  ['🍣', 'sushi'],
  ['🍱', 'bento comida japonesa'],
  ['🍤', 'camaron tempura shrimp'],
  ['🍙', 'arroz bola onigiri'],
  ['🍚', 'arroz rice'],
  ['🍛', 'curry arroz'],
  ['🍢', 'oden brocheta'],
  ['🥟', 'empanada dumpling'],
  ['🍦', 'helado cono ice cream'],
  ['🍨', 'helado ice cream'],
  ['🍧', 'raspado hielo'],
  ['🎂', 'pastel cumpleaños cake'],
  ['🍰', 'torta tarta cake'],
  ['🧁', 'cupcake magdalena'],
  ['🥧', 'pay pie'],
  ['🍫', 'chocolate'],
  ['🍬', 'caramelo dulce candy'],
  ['🍭', 'paleta dulce lollipop'],
  ['🍩', 'dona donut'],
  ['🍪', 'galleta cookie'],
  ['🍯', 'miel honey'],
  ['🥛', 'leche milk'],
  ['☕', 'cafe coffee'],
  ['🍵', 'te tea'],
  ['🧃', 'jugo caja juice'],
  ['🥤', 'refresco soda bebida'],
  ['🧋', 'bubble tea boba'],
  ['🍶', 'sake bebida'],
  ['🍺', 'cerveza beer'],
  ['🍻', 'cervezas brindis beer'],
  ['🍷', 'vino wine'],
  ['🥂', 'brindis champan'],
  ['🍸', 'coctel martini cocktail'],
  ['🍹', 'coctel tropical drink'],
  ['🥃', 'whisky vaso'],
  ['🍾', 'champan botella'],
  ['🧊', 'hielo cubo ice'],
  ['🥄', 'cuchara spoon'],
  ['🍴', 'cubiertos tenedor cuchillo fork'],
  ['🍽️', 'plato comida restaurante dinner'],
]);

const ACTIVITIES: EmojiEntry[] = entries([
  ['⚽', 'futbol soccer balon'],
  ['🏀', 'basket baloncesto'],
  ['🏈', 'futbol americano'],
  ['⚾', 'beisbol baseball'],
  ['🥎', 'softbol'],
  ['🎾', 'tenis tennis'],
  ['🏐', 'voleibol volleyball'],
  ['🏉', 'rugby'],
  ['🥏', 'frisbee disco'],
  ['🎱', 'billar pool'],
  ['🏓', 'ping pong tenis mesa'],
  ['🏸', 'badminton'],
  ['🥅', 'porteria goal'],
  ['🏒', 'hockey'],
  ['🏑', 'hockey cesped'],
  ['🥍', 'lacrosse'],
  ['🏏', 'cricket'],
  ['⛳', 'golf bandera'],
  ['🏹', 'arco flecha tiro'],
  ['🎣', 'pesca caña fishing'],
  ['🥊', 'boxeo guante boxing'],
  ['🥋', 'artes marciales karate'],
  ['🎽', 'correr camiseta running'],
  ['⛸️', 'patinaje hielo skate'],
  ['🥌', 'curling'],
  ['🛷', 'trineo sled'],
  ['🎿', 'esqui ski'],
  ['⛷️', 'esquiador ski'],
  ['🏂', 'snowboard'],
  ['🏋️', 'pesas gimnasio gym'],
  ['🤼', 'lucha wrestling'],
  ['🤸', 'gimnasia cartwheel'],
  ['⛹️', 'basket jugador'],
  ['🤺', 'esgrima fencing'],
  ['🏌️', 'golfista golf'],
  ['🏇', 'jinete carrera horse'],
  ['🧗', 'escalar climbing'],
  ['🚴', 'ciclismo bicicleta bike'],
  ['🚵', 'mountain bike ciclismo'],
  ['🏊', 'nadar swimming'],
  ['🤽', 'waterpolo'],
  ['🤾', 'balonmano handball'],
  ['🏄', 'surf'],
  ['🚣', 'remo bote rowing'],
  ['🤹', 'malabares juggling'],
  ['🎯', 'diana dardos target'],
  ['🎳', 'bolos bowling'],
  ['🎮', 'videojuego gamepad game'],
  ['🕹️', 'joystick arcade game'],
  ['🎲', 'dado dice juego'],
  ['🎰', 'tragamonedas slot'],
  ['🧩', 'rompecabezas puzzle'],
  ['♟️', 'ajedrez chess'],
  ['🎭', 'teatro mascaras drama'],
  ['🎨', 'arte pintura paleta art'],
  ['🎬', 'cine pelicula clapper movie'],
  ['🎤', 'microfono cantar mic'],
  ['🎧', 'audifonos musica headphones'],
  ['🎵', 'nota musica music'],
  ['🎶', 'notas musica music'],
  ['🎹', 'piano teclado'],
  ['🥁', 'tambor bateria drum'],
  ['🎷', 'saxofon sax'],
  ['🎺', 'trompeta trumpet'],
  ['🎸', 'guitarra guitar'],
  ['🎻', 'violin'],
  ['🪕', 'banjo'],
  ['🎼', 'partitura musica'],
  ['🎟️', 'entrada boleto ticket'],
  ['🎫', 'ticket entrada'],
  ['🎪', 'circo carpa circus'],
  ['🎨', 'arte paleta art'],
  ['🏆', 'trofeo premio trophy'],
  ['🥇', 'medalla oro gold'],
  ['🥈', 'medalla plata silver'],
  ['🥉', 'medalla bronce bronze'],
  ['🏅', 'medalla deportiva medal'],
  ['🎖️', 'medalla militar'],
  ['🎗️', 'lazo cinta ribbon'],
  ['🎉', 'fiesta confeti party'],
  ['🎊', 'confeti bola party'],
  ['🎈', 'globo balloon'],
  ['🎁', 'regalo gift presente'],
  ['🎀', 'lazo moño bow'],
  ['🎄', 'navidad arbol christmas'],
  ['🎃', 'halloween calabaza'],
  ['🧨', 'petardo firework'],
  ['🎆', 'fuegos artificiales fireworks'],
]);

const TRAVEL: EmojiEntry[] = entries([
  ['🚗', 'auto carro coche car'],
  ['🚕', 'taxi'],
  ['🚙', 'suv camioneta car'],
  ['🚌', 'bus autobus'],
  ['🚎', 'trolebus bus'],
  ['🏎️', 'auto carrera race car'],
  ['🚓', 'patrulla policia police car'],
  ['🚑', 'ambulancia ambulance'],
  ['🚒', 'bombero camion fire'],
  ['🚐', 'van furgoneta'],
  ['🚚', 'camion truck'],
  ['🚛', 'camion trailer truck'],
  ['🚜', 'tractor'],
  ['🏍️', 'moto motocicleta motorcycle'],
  ['🛵', 'scooter moto'],
  ['🚲', 'bicicleta bike'],
  ['🛴', 'patineta scooter'],
  ['🛹', 'patineta skate'],
  ['🚨', 'sirena alarma police'],
  ['🚔', 'patrulla police'],
  ['🚍', 'bus llegando'],
  ['🚝', 'monorriel tren'],
  ['🚄', 'tren bala train'],
  ['🚅', 'tren alta velocidad train'],
  ['🚈', 'tren ligero'],
  ['🚂', 'locomotora tren train'],
  ['🚆', 'tren train'],
  ['🚇', 'metro subway'],
  ['🚊', 'tranvia tram'],
  ['🚉', 'estacion tren station'],
  ['✈️', 'avion viaje vuelo plane'],
  ['🛫', 'despegue avion takeoff'],
  ['🛬', 'aterrizaje avion landing'],
  ['🛩️', 'avioneta plane'],
  ['🚁', 'helicoptero helicopter'],
  ['🚀', 'cohete rocket'],
  ['🛸', 'ovni platillo ufo'],
  ['⛵', 'velero barco sailboat'],
  ['🚤', 'lancha bote speedboat'],
  ['🛥️', 'yate motora'],
  ['🛳️', 'crucero barco ship'],
  ['⛴️', 'ferry barco'],
  ['🚢', 'barco ship'],
  ['⚓', 'ancla anchor'],
  ['⛽', 'gasolina combustible gas'],
  ['🚧', 'construccion obra'],
  ['🚦', 'semaforo traffic'],
  ['🚥', 'semaforo horizontal'],
  ['🗺️', 'mapa map'],
  ['🗿', 'moai estatua'],
  ['🗽', 'libertad estatua statue'],
  ['🗼', 'torre tokyo tower'],
  ['🏰', 'castillo castle'],
  ['🏯', 'castillo japones'],
  ['🏟️', 'estadio stadium'],
  ['🎡', 'rueda fortuna ferris'],
  ['🎢', 'montaña rusa roller'],
  ['🎠', 'carrusel carousel'],
  ['⛲', 'fuente fountain'],
  ['⛱️', 'sombrilla playa beach'],
  ['🏖️', 'playa beach'],
  ['🏝️', 'isla island'],
  ['🏜️', 'desierto desert'],
  ['🌋', 'volcan volcano'],
  ['⛰️', 'montaña mountain'],
  ['🏔️', 'montaña nieve mountain'],
  ['🗻', 'fuji montaña'],
  ['🏕️', 'campamento camping tienda'],
  ['⛺', 'tienda campaña tent'],
  ['🏠', 'casa home house'],
  ['🏡', 'casa jardin house'],
  ['🏢', 'oficina edificio office'],
  ['🏬', 'tienda departamental mall'],
  ['🏦', 'banco bank'],
  ['🏥', 'hospital salud'],
  ['🏨', 'hotel'],
  ['🏪', 'tienda conveniencia store'],
  ['🏫', 'escuela school'],
  ['⛪', 'iglesia church'],
  ['🕌', 'mezquita mosque'],
  ['🏛️', 'edificio clasico museo'],
  ['🌁', 'niebla ciudad fog'],
  ['🌃', 'noche ciudad night'],
  ['🌆', 'atardecer ciudad dusk'],
  ['🌇', 'atardecer sunset'],
  ['🌉', 'puente noche bridge'],
  ['🏙️', 'ciudad skyline city'],
]);

const OBJECTS: EmojiEntry[] = entries([
  ['⌚', 'reloj watch'],
  ['📱', 'celular telefono phone movil'],
  ['💻', 'laptop computadora computer'],
  ['🖥️', 'monitor pc desktop'],
  ['🖨️', 'impresora printer'],
  ['⌨️', 'teclado keyboard'],
  ['🖱️', 'mouse raton'],
  ['🕹️', 'joystick control'],
  ['💽', 'minidisc disco'],
  ['💾', 'disquete guardar save'],
  ['💿', 'cd disco'],
  ['📀', 'dvd disco'],
  ['📷', 'camara foto camera'],
  ['📸', 'camara flash'],
  ['📹', 'videocamara video'],
  ['🎥', 'camara cine movie'],
  ['📞', 'telefono llamada phone'],
  ['☎️', 'telefono phone'],
  ['📟', 'beeper pager'],
  ['📠', 'fax'],
  ['📺', 'television tv'],
  ['📻', 'radio'],
  ['🎙️', 'microfono estudio mic'],
  ['⏰', 'despertador alarma clock'],
  ['⏱️', 'cronometro stopwatch'],
  ['⏳', 'reloj arena hourglass'],
  ['🔋', 'bateria battery'],
  ['🔌', 'enchufe plug'],
  ['💡', 'bombilla idea light'],
  ['🔦', 'linterna flashlight'],
  ['🕯️', 'vela candle'],
  ['🧯', 'extintor fire'],
  ['🛢️', 'barril petroleo oil'],
  ['💸', 'dinero volando money'],
  ['💵', 'billete dolar money'],
  ['💴', 'billete yen'],
  ['💶', 'billete euro'],
  ['💷', 'billete libra'],
  ['💰', 'bolsa dinero money saco'],
  ['🪙', 'moneda coin'],
  ['💳', 'tarjeta credito card'],
  ['🧾', 'recibo factura receipt'],
  ['💎', 'diamante gema diamond'],
  ['⚖️', 'balanza justicia scale'],
  ['🧰', 'caja herramientas toolbox'],
  ['🔧', 'llave herramienta wrench'],
  ['🔨', 'martillo hammer'],
  ['⚒️', 'martillo pico tools'],
  ['🛠️', 'herramientas tools'],
  ['⛏️', 'pico mineria pick'],
  ['🔩', 'tuerca tornillo bolt'],
  ['⚙️', 'engranaje gear ajustes'],
  ['🧱', 'ladrillo brick'],
  ['⛓️', 'cadena chain'],
  ['🧲', 'iman magnet'],
  ['🔫', 'pistola arma gun'],
  ['💣', 'bomba bomb'],
  ['🔪', 'cuchillo knife'],
  ['🗡️', 'espada dagger'],
  ['🛡️', 'escudo shield'],
  ['🚬', 'cigarro fumar'],
  ['⚰️', 'ataud coffin'],
  ['🏺', 'anfora vasija'],
  ['🔮', 'bola cristal magia crystal'],
  ['📿', 'rosario beads'],
  ['💈', 'barberia barber'],
  ['🔭', 'telescopio telescope'],
  ['🔬', 'microscopio microscope'],
  ['🩺', 'estetoscopio salud medico'],
  ['💊', 'pastilla medicina pill'],
  ['💉', 'jeringa vacuna syringe'],
  ['🩹', 'curita venda bandage'],
  ['🌡️', 'termometro temperature'],
  ['🧪', 'tubo ensayo quimica'],
  ['🧬', 'adn dna'],
  ['🦠', 'microbio virus'],
  ['🧫', 'placa petri'],
  ['🧴', 'botella locion lotion'],
  ['🧷', 'imperdible pin'],
  ['🧹', 'escoba broom'],
  ['🧺', 'cesta canasta basket'],
  ['🧻', 'papel higienico'],
  ['🧼', 'jabon soap'],
  ['🧽', 'esponja sponge'],
  ['🚪', 'puerta door'],
  ['🛏️', 'cama bed'],
  ['🛋️', 'sofa couch'],
  ['🪑', 'silla chair'],
  ['🚽', 'inodoro wc toilet'],
  ['🚿', 'ducha shower'],
  ['🛁', 'tina baño bath'],
  ['🧸', 'oso peluche teddy'],
  ['🖼️', 'cuadro marco frame'],
  ['🛒', 'carrito compras cart super'],
  ['🎒', 'mochila backpack'],
  ['👜', 'bolso bag cartera'],
  ['👛', 'monedero purse'],
  ['👝', 'bolsa pouch'],
  ['💼', 'maletin trabajo briefcase'],
  ['🧳', 'maleta equipaje luggage'],
  ['👓', 'gafas lentes glasses'],
  ['🕶️', 'gafas sol sunglasses'],
  ['👔', 'corbata camisa tie'],
  ['👕', 'camiseta ropa shirt'],
  ['👖', 'pantalon jeans'],
  ['👗', 'vestido dress'],
  ['👞', 'zapato shoe'],
  ['👟', 'tenis zapatilla sneaker'],
  ['👠', 'tacon heel'],
  ['👑', 'corona crown rey'],
  ['🎩', 'sombrero top hat'],
  ['🧢', 'gorra cap'],
  ['⛑️', 'casco rescate helmet'],
  ['💍', 'anillo ring'],
  ['👒', 'sombrero sol hat'],
  ['📚', 'libros books educacion'],
  ['📖', 'libro abierto book'],
  ['📕', 'libro rojo book'],
  ['📓', 'cuaderno notebook'],
  ['📔', 'diario notebook'],
  ['📒', 'libreta ledger'],
  ['📃', 'documento pagina page'],
  ['📄', 'hoja pagina document'],
  ['📑', 'marcadores bookmark'],
  ['📊', 'grafico barras chart'],
  ['📈', 'grafico subida inversion chart up'],
  ['📉', 'grafico bajada chart down'],
  ['📰', 'periodico noticias news'],
  ['📅', 'calendario calendar'],
  ['📆', 'calendario fecha calendar'],
  ['🗓️', 'calendario spiral'],
  ['📋', 'portapapeles clipboard'],
  ['📌', 'chincheta pin'],
  ['📍', 'ubicacion pin location'],
  ['📎', 'clip paperclip'],
  ['✂️', 'tijeras scissors'],
  ['📐', 'escuadra regla ruler'],
  ['📏', 'regla ruler'],
  ['🖊️', 'boligrafo pen'],
  ['✏️', 'lapiz pencil'],
  ['🖍️', 'crayon'],
  ['🖌️', 'pincel brush'],
  ['📝', 'nota escribir memo'],
  ['🗒️', 'libreta notas notepad'],
  ['🗂️', 'archivador folders'],
  ['📁', 'carpeta folder'],
  ['📂', 'carpeta abierta folder'],
  ['🗃️', 'archivo card box'],
  ['🗄️', 'archivador file cabinet'],
  ['📦', 'caja paquete box package'],
  ['📫', 'buzon mailbox'],
  ['📮', 'buzon correo postbox'],
  ['✉️', 'sobre correo email'],
  ['📧', 'email correo mail'],
  ['📨', 'correo entrante mail'],
  ['🔑', 'llave key'],
  ['🗝️', 'llave antigua key'],
  ['🔒', 'candado cerrado lock'],
  ['🔓', 'candado abierto unlock'],
  ['🔐', 'candado llave secure'],
  ['🔔', 'campana bell notificacion'],
  ['🔕', 'campana silencio mute'],
  ['📢', 'altavoz megafono announce'],
  ['📣', 'megafono speaker'],
]);

const SYMBOLS: EmojiEntry[] = entries([
  ['❤️', 'corazon rojo amor love heart'],
  ['🧡', 'corazon naranja heart'],
  ['💛', 'corazon amarillo heart'],
  ['💚', 'corazon verde heart'],
  ['💙', 'corazon azul heart'],
  ['💜', 'corazon morado heart'],
  ['🖤', 'corazon negro heart'],
  ['🤍', 'corazon blanco heart'],
  ['🤎', 'corazon marron heart'],
  ['💔', 'corazon roto broken heart'],
  ['❣️', 'corazon exclamacion heart'],
  ['💕', 'dos corazones hearts'],
  ['💞', 'corazones girando hearts'],
  ['💓', 'corazon latido heartbeat'],
  ['💗', 'corazon creciendo heart'],
  ['💖', 'corazon brillante sparkle heart'],
  ['💘', 'corazon flecha cupido'],
  ['💝', 'corazon regalo gift heart'],
  ['💟', 'decoracion corazon'],
  ['☮️', 'paz peace'],
  ['✝️', 'cruz cristiana cross'],
  ['☪️', 'islam luna estrella'],
  ['🕉️', 'om hinduismo'],
  ['☯️', 'yin yang'],
  ['♈', 'aries zodiaco'],
  ['♉', 'tauro zodiaco'],
  ['♊', 'geminis zodiaco'],
  ['♋', 'cancer zodiaco'],
  ['♌', 'leo zodiaco'],
  ['♍', 'virgo zodiaco'],
  ['♎', 'libra zodiaco'],
  ['♏', 'escorpio zodiaco'],
  ['♐', 'sagitario zodiaco'],
  ['♑', 'capricornio zodiaco'],
  ['♒', 'acuario zodiaco'],
  ['♓', 'piscis zodiaco'],
  ['🆔', 'id identificacion'],
  ['⚛️', 'atomo ciencia atom'],
  ['🉑', 'aceptable japones'],
  ['☢️', 'radiactivo radiation'],
  ['☣️', 'biopeligro biohazard'],
  ['📵', 'no celular phone off'],
  ['🚯', 'no basura litter'],
  ['🚱', 'agua no potable'],
  ['🚭', 'no fumar no smoking'],
  ['❗', 'exclamacion importante'],
  ['❓', 'pregunta question'],
  ['❕', 'exclamacion blanca'],
  ['❔', 'pregunta blanca'],
  ['‼️', 'doble exclamacion'],
  ['⁉️', 'interrobang'],
  ['💯', 'cien puntos perfecto 100'],
  ['🔅', 'brillo bajo dim'],
  ['🔆', 'brillo alto bright'],
  ['✅', 'check verde correcto ok'],
  ['☑️', 'casilla check'],
  ['✔️', 'palomita check'],
  ['❌', 'equis incorrecto error x'],
  ['❎', 'equis verde cross'],
  ['➕', 'mas suma plus add'],
  ['➖', 'menos resta minus'],
  ['➗', 'division divide'],
  ['✖️', 'multiplicacion x'],
  ['💲', 'dolar simbolo dollar'],
  ['💱', 'cambio divisa currency'],
  ['™️', 'marca trademark'],
  ['©️', 'copyright'],
  ['®️', 'registrado registered'],
  ['〰️', 'onda linea'],
  ['➰', 'rizo loop'],
  ['🔚', 'fin end'],
  ['🔙', 'atras back'],
  ['🔛', 'on encendido'],
  ['🔝', 'arriba top'],
  ['🔜', 'pronto soon'],
  ['🔁', 'repetir repeat loop'],
  ['🔂', 'repetir una vez'],
  ['🔄', 'recargar refresh sync'],
  ['▶️', 'play reproducir'],
  ['⏸️', 'pausa pause'],
  ['⏹️', 'detener stop'],
  ['⏺️', 'grabar record'],
  ['⏭️', 'siguiente next'],
  ['⏮️', 'anterior previous'],
  ['🔀', 'aleatorio shuffle'],
  ['🔊', 'volumen alto speaker'],
  ['🔇', 'silencio mute'],
  ['⭕', 'circulo rojo o'],
  ['🔴', 'circulo rojo red'],
  ['🟠', 'circulo naranja'],
  ['🟡', 'circulo amarillo'],
  ['🟢', 'circulo verde'],
  ['🔵', 'circulo azul'],
  ['🟣', 'circulo morado'],
  ['⚫', 'circulo negro'],
  ['⚪', 'circulo blanco'],
  ['🟥', 'cuadrado rojo'],
  ['🟧', 'cuadrado naranja'],
  ['🟨', 'cuadrado amarillo'],
  ['🟩', 'cuadrado verde'],
  ['🟦', 'cuadrado azul'],
  ['⬛', 'cuadrado negro'],
  ['⬜', 'cuadrado blanco'],
  ['🔶', 'rombo naranja diamond'],
  ['🔷', 'rombo azul diamond'],
  ['🔸', 'rombo pequeño naranja'],
  ['🔹', 'rombo pequeño azul'],
  ['⭐', 'estrella star'],
  ['🌟', 'estrella brillante'],
  ['💫', 'mareo estrella dizzy'],
  ['⚠️', 'advertencia warning peligro'],
  ['🚸', 'niños cruzando children'],
  ['🔰', 'principiante novato'],
  ['♻️', 'reciclar recycle'],
  ['✳️', 'asterisco'],
  ['❇️', 'destello sparkle'],
  ['🔱', 'tridente trident'],
  ['📛', 'gafete nombre badge'],
  ['🆚', 'versus vs'],
  ['🅰️', 'a sangre'],
  ['🆎', 'ab sangre'],
  ['🅱️', 'b sangre'],
  ['🆑', 'cl despejar'],
  ['🆒', 'cool genial'],
  ['🆓', 'free gratis'],
  ['🆕', 'new nuevo'],
  ['🆖', 'ng'],
  ['🅾️', 'o sangre'],
  ['🆗', 'ok'],
  ['🆘', 'sos ayuda emergencia'],
  ['🆙', 'up subir'],
  ['#️⃣', 'numeral hashtag'],
  ['*️⃣', 'asterisco'],
  ['0️⃣', 'cero 0'],
  ['1️⃣', 'uno 1'],
  ['2️⃣', 'dos 2'],
  ['3️⃣', 'tres 3'],
  ['4️⃣', 'cuatro 4'],
  ['5️⃣', 'cinco 5'],
  ['6️⃣', 'seis 6'],
  ['7️⃣', 'siete 7'],
  ['8️⃣', 'ocho 8'],
  ['9️⃣', 'nueve 9'],
  ['🔟', 'diez 10'],
]);

const FREQUENT: EmojiEntry[] = FREQUENT_EMOJIS.map((char) => ({
  char,
  keywords: 'frecuente',
}));

export const EMOJI_GROUPS: EmojiGroup[] = [
  { id: 'frequent', label: 'Frecuentes', emojis: FREQUENT },
  { id: 'faces', label: 'Caras', emojis: FACES },
  { id: 'gestures', label: 'Personas', emojis: GESTURES },
  { id: 'nature', label: 'Naturaleza', emojis: NATURE },
  { id: 'food', label: 'Comida', emojis: FOOD },
  { id: 'activities', label: 'Actividades', emojis: ACTIVITIES },
  { id: 'travel', label: 'Viajes', emojis: TRAVEL },
  { id: 'objects', label: 'Objetos', emojis: OBJECTS },
  { id: 'symbols', label: 'Simbolos', emojis: SYMBOLS },
];

export function searchEmojis(query: string): EmojiEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const seen = new Set<string>();
  const results: EmojiEntry[] = [];
  for (const group of EMOJI_GROUPS) {
    if (group.id === 'frequent') continue;
    for (const entry of group.emojis) {
      if (seen.has(entry.char)) continue;
      if (entry.char === q || entry.keywords.includes(q)) {
        seen.add(entry.char);
        results.push(entry);
      }
    }
  }
  return results;
}
